### ISSUE TITLE
Unable to clean modules installed by xcaddy build

### ISSUE THREAD

**Issue by akeskimo** [caddyserver/xcaddy#102]
While building with xcaddy with Yocto I am getting the following error

`ERROR: Command '['rm', '-rf', '/work/yocto/build/tmp/work/aarch64-poky-linux/caddy/2.4.6-r0/build/pkg']' returned non-zero exit status 1.`

In our build machine, we need write access to modules directory in order to re-compile the project but go modules are installed with read access, only. This can be fixed by executing go build with flag '-modcacherw` but xcaddy does not support passing custom flags from environment.

**Comment by akeskimo** [comment]
The flag `modcacherw` has been introduced since go1.4 and sets write bit on pulled go modules. Certain build tools will try to clean up the modules directory and do not have root priviledges so it would be convenient to add this support for xcaddy.

**Comment by akeskimo** [comment]
The command I am executing is 

`xcaddy build e7457b43e4703080ae8713ada798ce3e20b83690 --with github.com/ggicci/caddy-jwt@v0.7.1`

which works just fine for the first time. It fails in consequent runs because the build system must clean the files before it can be re-compiled but it fails because go installs modules as RO which causes rm to bail out.

**Comment by akeskimo** [comment]
There is also another related issue with xcaddy is that Yocto trims the produced binaries automatically but xcaddy enforces this by adding flags 

builder.go
```
cmd.Args = append(cmd.Args,
	"-ldflags", "-w -s", // trim debug symbols
	"-trimpath",
)
```

so I will need to add the following exception to my recipe

```
# Binaries procuded by xcaddy are stripped already which would cause QA error during build so we can safely ignore this warning.
INSANE_SKIP_${PN} += "already-stripped"
```

This could be avoided if there would be an environment variable that could allow user to pass the build flags to xcaddy which would allow the user to control the behavior of compilation.

**Comment by mholt** [comment]
>  It fails in consequent runs because the build system must clean the files before it can be re-compiled

Sorry, I don't understand. Go doesn't delete files to re-compile a second time.

This sounds like more of a problem with whatever Yocto is, than xcaddy or Go. 🤔

**Comment by akeskimo** [comment]
> Sorry, I don't understand. Go doesn't delete files to re-compile a second time.

Yocto is a distributed build-system to compile Linux kernels which are used by millions of Embedded Linux devices. Yes, you are correct: Go does not delete files during recompiling, but a build system might.

> This sounds like more of a problem with whatever Yocto is, than xcaddy or Go. thinking

No, this is not an issue with Go or Yocto. Let me explain.

Go installs modules with read-only access (by default) because Golang was developed by Google who uses monolithic repository structure which can benefit from using global module path. The global module install cannot be used for distributed build-systems because modules need to declare their own dependencies which would blow up in disk space. Fortunately, this has been addressed by Golang maintainers long time ago by introducing flag `modcacherw` which xcaddy seems to be ignoring, for some reason.

Here is background information and discussion related to why the flag is needed https://gitlab.com/gitlab-org/gitlab-development-kit/-/issues/1447.

**Comment by akeskimo** [comment]
In Caddy-speak, what I need is something like this

`env XCADDY_GOBUILDFLAGS="-ldflags -w -s" xcaddy build e7457b43e4703080ae8713ada798ce3e20b83690 --with github.com/ggicci/caddy-jwt@v0.7.1`

which allows me to redefine build arguments from our build system.

I have already patched this in our build system but I decided to bring this up because the caddy community would benefit from it.

**Comment by mholt** [comment]
Oh, I see what you mean now. Thanks for the explanation. Yeah, that env var seems like a good way to work around it, I guess. (I'm way less picky about xcaddy than I am about caddy anyway.) Want to submit a PR?

**Comment by akeskimo** [comment]
Sure, the patch needs a bit of polishing but I should be able to submit it by next week.

**Comment by akeskimo** [comment]
I am not sure what is your process for contributing so I created a fork for the pull request. You can comment on the PR if any changes are needed.

**Comment by akeskimo** [comment]
Hi @mholt,

We still have the problem that go modules that are pulled in by go get or go mod might be read-only which we are unable to clean from our build environment. I have added another pull request which should fully resolve this issue. We currently have this patch applied in our build system (Yocto) but here it is if you would like to have this in upstream, as well.
