### ISSUE TITLE
Xcaddy build fails with any module

### ISSUE THREAD

**Issue by Un3x** [caddyserver/xcaddy#105]
Hello there,
I've recently tried to build caddy to work both with mercure and digitalocean and it seems I have a weird error I cannot find any clues on.

I'm trying to run caddy with the mercure submodule, but I need to make it work with digital ocean, I also have my symfony webserver running on nginx. So the caddy build is only meant to run for mercure.
I've tried to used the provided caddy build with mercure but it lacks the digitalocean submodule required to generate the ssl certificates. 

So I figured out I would need to build caddy with both mercure and digital ocean submodule.

Basically here is the build command
``` xcaddy build --with github.com/caddy-dns/digitalocean --with github.com/dunglas/mercure --with github.com/dunglas/mercure/caddy --output mercure```

And I get an error incoming from go 
```
2022/06/24 12:44:14 [INFO] Initializing Go module
2022/06/24 12:44:14 [INFO] exec (timeout=10s): /usr/bin/go mod init caddy 
go: creating new go.mod: module caddy
2022/06/24 12:44:14 [INFO] Pinning versions
2022/06/24 12:44:14 [INFO] exec (timeout=0s): /usr/bin/go get -d -v github.com/caddyserver/caddy/v2 
2022/06/24 12:44:16 [INFO] exec (timeout=0s): /usr/bin/go get -d -v github.com/caddy-dns/digitalocean github.com/caddyserver/caddy/v2 
go: finding github.com/caddy-dns/digitalocean latest
2022/06/24 12:44:17 [INFO] exec (timeout=0s): /usr/bin/go get -d -v github.com/dunglas/mercure github.com/caddyserver/caddy/v2 
2022/06/24 12:44:18 [INFO] exec (timeout=0s): /usr/bin/go get -d -v github.com/dunglas/mercure/caddy github.com/caddyserver/caddy/v2 
2022/06/24 12:44:19 [INFO] exec (timeout=0s): /usr/bin/go get -d -v  
2022/06/24 12:44:21 [INFO] Build environment ready
2022/06/24 12:44:21 [INFO] Building Caddy
2022/06/24 12:44:21 [INFO] exec (timeout=0s): /usr/bin/go mod tidy 
caddy imports
        github.com/dunglas/mercure imports
        embed: malformed module path "embed": missing dot in first path element
caddy imports
        github.com/dunglas/mercure imports
        io/fs: malformed module path "io/fs": missing dot in first path element
caddy imports
        github.com/dunglas/mercure imports
        github.com/prometheus/client_golang/prometheus imports
        runtime/metrics: malformed module path "runtime/metrics": missing dot in first path element
caddy imports
        github.com/dunglas/mercure imports
        github.com/spf13/viper imports
        github.com/spf13/afero tested by
        github.com/spf13/afero.test imports
        testing/fstest: malformed module path "testing/fstest": missing dot in first path element
2022/06/24 12:44:21 [INFO] Cleaning up temporary folder: /tmp/buildenv_2022-06-24-1244.3377567355
2022/06/24 12:44:21 [FATAL] exit status 1
```

Both go and xcaddy are up to date and wondered if this is a known issue or a weird error on my side ?

Go version : ```go version go1.13.8 linux/amd64```
Xcaddy version : ```v0.3.0 h1:3LTHAhHb5YKKqTLLj8kdF9cfGMl4jHV4uRbtw7LBJ6k=```

I also tried to build caddy with each submodule separatly to see if it was only one of them having an issue, but I get each time a similar error on different packages depending on the provided submodules.

If you need more informations on whats going on, I'll be happy to provide.

**Comment by mholt** [comment]
Looks like you have a very old version of Go. Please upgrade your Go version to 1.18.
