### ISSUE TITLE
go: cannot match "all": go.mod file not found

### ISSUE THREAD

**Issue by roukmoute** [caddyserver/xcaddy#106]
<pre>
$ go version
go version go1.18.3 linux/amd64
</pre>

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/roukmoute/.cache/go-build"
GOENV="/home/roukmoute/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/roukmoute/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/roukmoute/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build239843618=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

Just try to use xcaddy.

https://asciinema.org/a/507891

### What did you expect to see?

A converted file

### What did you see instead?

```sh
go: cannot match "all": go.mod file not found in current directory or any parent directory; see 'go help modules'
2022/07/12 07:01:47 [ERROR] exec [go list -m -json all]: exit status 1: 
```

**Comment by francislavoie** [comment]
You ran `xcaddy adapt`... What do you expect to happen exactly?

If you run `xcaddy` with anything other than `xcaddy build`, you're using it in dev mode, which expects a go.mod to be found in the current directory, i.e. to make a build of Caddy plus the plugin in the current directory. This is a tool for plugin developers.

Looks like you're trying to adapt an nginx config. That requires the nginx-adapter plugin. For that, you would build Caddy with `xcaddy build --with github.com/caddyserver/nginx-adapter`, and then use `./caddy`, the built binary, to run it.

**Comment by roukmoute** [comment]
Ok thanks!

I'm beginning in `go` and all this stuff is a little bit confusing.

**Comment by thenitai** [comment]
This should be mentioned in the documentation as just about everyone after the installation types "xcaddy" runs into this "error". Would go a long way :)

**Comment by mholt** [comment]
@thenitai The docs do mention this behavior:

> If you run xcaddy from within the folder of the Caddy plugin you're working on without the build subcommand, it will build Caddy with your current module and run it, as if you manually plugged it in and invoked go run.

**Comment by thenitai** [comment]
> [@thenitai](https://github.com/thenitai) The docs do mention this behavior:
> 
> > If you run xcaddy from within the folder of the Caddy plugin you're working on without the build subcommand, it will build Caddy with your current module and run it, as if you manually plugged it in and invoked go run.

Right. But even as a developer but never played with Go I've had to search around and look for a solution. As mention, no worries, all good. It's up and running. Thank you.
