### ISSUE TITLE
xcaddy option to build with local module without deleting build afterwards

### ISSUE THREAD

**Issue by jason-jackson** [caddyserver/xcaddy#108]
Right now you can "build" your local module to see if it compiles with just `xcaddy`, but it "conveniently" deletes the build afterwards. It would be helpful to have an option to build caddy with the local module and not delete the build afterwards.

Proposal: use `xcaddy build` to build caddy with local modules if they exist.

**Comment by francislavoie** [comment]
You can use this pattern instead:

```
$ xcaddy build --with github.com/your/plugin=.
```

**Comment by mohammed90** [comment]
Also, there's the env var `XCADDY_SKIP_CLEANUP` for that purpose.

**Comment by jason-jackson** [comment]
`XCADDY_SKIP_CLEANUP` was what I was looking for, but missed seeing it at bottom of README. Thanks!
