### ISSUE TITLE
"at sign (@)" in local fork path trips up module path

### ISSUE THREAD

**Issue by devinark** [caddyserver/xcaddy#109]
With a project like this:

```sh
$ pwd
# /home/devin/projects/@relay/caddy-bin
$ ls ..
# caddy-bin
# caddy-dns-cloudflare
$ xcaddy build --with github.com/caddy-dns/cloudflare=../caddy-dns-cloudflare
```
The build fails with this error:
```sh
/tmp/buildenv_2022-07-28-1550.3872914361/go.mod:5: malformed module path "/home/devin/projects/": trailing slash
```

If I symlink the fork directory outside of the `@relay` directory and specify the absolute path to the symlink instead of the relative one, xcaddy builds correctly. I understand this might come from the simple implementation tied to go modules, but it would be better if xcaddy worked with any local directory name.

**Comment by mholt** [comment]
@devinark Yeah, I mean, Go doesn't like `@` in package paths either

```
$ go get github.com/@mholt/foo
go: github.com@mholt/foo: invalid version: version "mholt/foo" invalid: disallowed version tring
```

If you want support for `@` in package paths, you probably want to take the issue [upstream with the Go project](https://github.com/golang/go).

**Comment by mholt** [comment]
Oh, but maybe this is about a file path and not a module path... will give this a second look.

**Comment by mholt** [comment]
Ok, well not gonna lie this is kind of a weird one :confounded: 

`xcaddy` will handle paths with `@` in them now, but it requires that a version is also specified at the end using the usual `@version` syntax for Go modules. This is to disambiguate; if there's more than one `@` then we know the last one is the version.
