### ISSUE TITLE
Will xcaddy be able to do cross-compilation?

### ISSUE THREAD

**Issue by JACK-THINK** [caddyserver/xcaddy#11]
Hello,

I notice that there is no `caddy_2.0.0_linux_armv5.tar.gz` in [official distributions](https://github.com/caddyserver/caddy/releases). Will xcaddy be able to do cross-compilation? Or is it possible to add a `caddy_2.0.0_linux_armv5.tar.gz` to official distributions?

Thanks a lot.

**Comment by mholt** [comment]
Yep, just like the README says:

> As usual with go command, the xcaddy command will pass the GOOS, GOARCH, and GOARM environment variables through for cross-compilation.

So:

```
GOOS=windows xcaddy ...
```

would cross-compile for Windows.
