### ISSUE TITLE
installation command returns 404

### ISSUE THREAD

**Issue by tonyzorin** [caddyserver/xcaddy#114]
Go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest returns empty response, nothing gets installed.
If to open github.com/caddyserver/xcaddy/cmd/xcaddy@latest in browser, it returns 404.

**Comment by francislavoie** [comment]
> If to open github.com/caddyserver/xcaddy/cmd/xcaddy@latest in browser, it returns 404.

That's not a real URL. It's a Go module path.

Do you actually have Go installed? What version of Go? Run `go version` to check. You should have at least 1.18 or ideally 1.19.

**Comment by tonyzorin** [comment]
$ go version
go version go1.18.3 linux/amd64

Caddy is running on an Amazon Linux.

**Comment by francislavoie** [comment]
Works just fine for me:

```
$ go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
go: downloading github.com/caddyserver/xcaddy v0.3.0
```

Not on AMI though. But you haven't shown us an error or anything, so we can't do much here.

You can just download the binary from the GitHub releases tab if you can't figure it out otherwise.
