### ISSUE TITLE
xcaddy run with go 19 does not work

### ISSUE THREAD

**Issue by ydylla** [caddyserver/xcaddy#116]
Hi,
when I try to run `xcaddy run -config foo.json` in the root directory of [caddy-l4](https://github.com/mholt/caddy-l4) I get the following error:
```
2022/09/09 23:50:15 [ERROR] exec: "caddy.exe": cannot run executable found relative to current directory
```
I found https://github.com/golang/go/issues/53962 and the workaround via setting the `GODEBUG=execerrdot=0` environment variable works.  
Can xcaddy fix this in a better way?

**Comment by mholt** [comment]
Huh, I can't reproduce this error, using Go 1.19 (including xcaddy built on Go 1.19). Does it only happen on Windows?
