### ISSUE TITLE
How to update to latest when installed from source

### ISSUE THREAD

**Issue by timkgh** [caddyserver/xcaddy#119]
Maybe this is more of a general Go question, but at some point I installed xcaddy from source using
`go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest`

What's the proper way to update to the latest version, running the above again does not seem to do anything, I still get v0.3.0 when I'd expect v0.3.1
```
> go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

> go/bin/xcaddy version
v0.3.0 h1:3LTHAhHb5YKKqTLLj8kdF9cfGMl4jHV4uRbtw7LBJ6k=
```

```
> go version
go version go1.19.1 darwin/amd64
```

**Comment by timkgh** [comment]
`go clean -modcache` and then install `@latest` fixed it, but I'm confused why the above didn't work.

**Comment by mholt** [comment]
Honestly, I have no clue, haha. Go modules are still a bit of a black box to me. Thanks for posting your solution!
