### ISSUE TITLE
xcaddy_0.3.1_windows_arm64: doesn't run

### ISSUE THREAD

**Issue by AntonOks** [caddyserver/xcaddy#120]
This one:
https://github.com/caddyserver/xcaddy/releases/download/v0.3.1/xcaddy_0.3.1_windows_arm64.zip

doesn't run on my Win10 PRO ARM based Miix630. Error is:
```
λ  .\xcaddy.exe
go: cannot match "all": go.mod file not found in current directory or any parent directory; see 'go help modules'
2022/10/10 17:21:01 [ERROR] exec [go list -m -json all]: exit status 1:
```

**Comment by mholt** [comment]
Looks like xcaddy is running fine. I don't know what the problem is with that information, we'd need to be able to reproduce this from scratch. Make sure you're running the latest Go version and your Go project is set up correctly.

**Comment by AntonOks** [comment]
> Looks like xcaddy is running fine. I don't know what the problem is with that information, we'd need to be able to reproduce this from scratch. Make sure you're running the latest Go version and your Go project is set up correctly.

???

I have a ARM based Windows box.
I download your xcaddy ARM64 artifact / release, extract it to a new directory and run the xcaddy.exe binary... which results in the given error.

Si, I run just the binary. What has this to do with any GO version I may or may not have installed?

**Comment by mohammed90** [comment]
> > Looks like xcaddy is running fine. I don't know what the problem is with that information, we'd need to be able to reproduce this from scratch. Make sure you're running the latest Go version and your Go project is set up correctly.
> 
> ???
> 
> I have a ARM based Windows box.
> I download your xcaddy ARM64 artifact / release, extract it to a new directory and run the xcaddy.exe binary... which results in the given error.
> 
> Si, I run just the binary. What has this to do with any GO version I may or may not have installed?

The output you shared is generated from xcaddy itself. Can you share what you are trying to do, what the current directory contains, and your intended goal? I believe there's a confusion of what xcaddy does or what you're expecting it to do on its own.

**Comment by AntonOks** [comment]
> > > Looks like xcaddy is running fine. I don't know what the problem is with that information, we'd need to be able to reproduce this from scratch. Make sure you're running the latest Go version and your Go project is set up correctly.
> > 
> > 
> > ???
> > I have a ARM based Windows box.
> > I download your xcaddy ARM64 artifact / release, extract it to a new directory and run the xcaddy.exe binary... which results in the given error.
> > Si, I run just the binary. What has this to do with any GO version I may or may not have installed?
> 
> The output you shared is generated from xcaddy itself. Can you share what you are trying to do, what the current directory contains, and your intended goal? I believe there's a confusion of what xcaddy does or what you're expecting it to do on its own.

I just want to run the xcaddy binary on my ARM based Windows 10 PRO system. That's that simple!!!
The ARM64 binary is not running on an ARM based Windows 10 PRO. 
It's not about "doing something wrong". The binary is not starting / running / executed... that simple.

I use xcaddy on another Windows X64 systems since... ever. Again, this here is about "the ARM64 xcaddy binary is NOT running at all"...

**Comment by AntonOks** [comment]
... and please re-open this issue.

Thanks!

**Comment by mholt** [comment]
> I just want to run the xcaddy binary on my ARM based Windows 10 PRO system. That's that simple!!!
> The ARM64 binary is not running on an ARM based Windows 10 PRO.
> It's not about "doing something wrong". The binary is not starting / running / executed... that simple.

False. That error is generated by xcaddy trying to invoke `go list -m -json all` which is returning an error related to your local Go project setup.

When you are ready to cooperate we can reopen this issue if it is a bug. Please kindly answer Mohammed's questions so we can help you.

**Comment by francislavoie** [comment]
See the readme. It seems like you're using it incorrectly.

The usecase of using it with no arguments only works if you're currently inside the directory of a plugin you're building.

If you're trying to use it to make a build of Caddy (not plugin development) then you must use the `build` command.

**Comment by AntonOks** [comment]
holly cow. sorry for the noise, I wanted to run __CADDY__ on my ARM64 box as I do on some other "servers" as well... have no idea how I mixed it up with __Xcaddy__ now. Guess I need some sleep...

Again, sorry and thanks for your patience....
