### ISSUE TITLE
External module

### ISSUE THREAD

**Issue by alancolant** [caddyserver/xcaddy#121]
I think I have a problem with the use of external libraries.

I need the govips library. But each `xcaddy run` or `xcaddy build` command fails with this error:
```
---/caddyfileproxy.go:45:2: undefined: vips
---/CADDY_FILE_SERVER/caddyfileproxy.go:46:8: undefined: vips
---/CADDY_FILE_SERVER/caddyfileproxy.go:48:17: undefined: vips
```

But I have correct import in my file:
```go
import (
	"fmt"
	"github.com/caddyserver/caddy/v2"
	"github.com/caddyserver/caddy/v2/modules/caddyhttp"
	"github.com/davidbyttow/govips/v2/vips"
	"net/http"
)
```

And the package is present in my go.mod file:
```golang
module ---
go 1.19

require github.com/caddyserver/caddy/v2 v2.6.1
require github.com/davidbyttow/govips/v2 v2.11.0
```

You can find all sources here: https://gitlab.com/alancolant/caddy-file-server
Do you know the reason?

**Comment by francislavoie** [comment]
Seems like vips needs CGO to compile. `xcaddy` turns off CGO by default IIRC. You might need to play with that, I guess.

**Comment by francislavoie** [comment]
I guess I'll close this as inactive.
