### ISSUE TITLE
fails: "You may also build xcaddy from source"

### ISSUE THREAD

**Issue by eidenschink** [caddyserver/xcaddy#123]
I used `go install` and it returned without further notice. Then again with `-x` it shows the 404's:

```
# go install -x github.com/caddyserver/xcaddy/cmd/xcaddy@latest

# get https://proxy.golang.org/github.com/caddyserver/@v/list
# get https://proxy.golang.org/github.com/caddyserver/xcaddy/@v/list
# get https://proxy.golang.org/github.com/caddyserver/xcaddy/cmd/xcaddy/@v/list
# get https://proxy.golang.org/github.com/@v/list
# get https://proxy.golang.org/github.com/caddyserver/xcaddy/cmd/@v/list
# get https://proxy.golang.org/github.com/caddyserver/xcaddy/cmd/xcaddy/@v/list: 404 Not Found (0.173s)
# get https://proxy.golang.org/github.com/@v/list: 404 Not Found (0.174s)
# get https://proxy.golang.org/github.com/caddyserver/xcaddy/@v/list: 200 OK (0.174s)
# get https://proxy.golang.org/github.com/caddyserver/@v/list: 404 Not Found (0.174s)
# get https://proxy.golang.org/github.com/caddyserver/xcaddy/cmd/@v/list: 404 Not Found (0.176s)
```

**Comment by yelnyafacee** [comment]
@eidenschink hi, did u managed to find a solution for this? I am stucked here too, it shows no notice :(

**Comment by mholt** [comment]
I just ran that command and it worked for me :man_shrugging: 

It's strange that Go is thinking the version string is blank (`@v/`). Make sure your proxy settings are correct, maybe?

**Comment by mholt** [comment]
Oh wow, yeah, a space does it. Nice find.

**Comment by mohammed90** [comment]
> the spaces does not seems to solve it for me, still getting 404 error, unable to install `xcaddy` :(
> 
> ```
> [root@vultrguest ~]# go install -x github.com/caddyserver/xcaddy/cmd/xcaddy@latest  
> # get https://proxy.golang.org/github.com/caddyserver/xcaddy/cmd/xcaddy/@v/list
> # get https://proxy.golang.org/github.com/caddyserver/xcaddy/cmd/@v/list
> # get https://proxy.golang.org/github.com/caddyserver/xcaddy/@v/list
> # get https://proxy.golang.org/github.com/caddyserver/@v/list
> # get https://proxy.golang.org/github.com/@v/list
> # get https://proxy.golang.org/github.com/@v/list: 404 Not Found (0.017s)
> # get https://proxy.golang.org/github.com/caddyserver/xcaddy/cmd/xcaddy/@v/list: 404 Not Found (0.268s)
> # get https://proxy.golang.org/github.com/caddyserver/@v/list: 404 Not Found (0.290s)
> # get https://proxy.golang.org/github.com/caddyserver/xcaddy/cmd/@v/list: 404 Not Found (0.293s)
> # get https://proxy.golang.org/github.com/caddyserver/xcaddy/@v/list: 200 OK (0.317s)
> WORK=/tmp/go-build4213658272
> [root@vultrguest ~]# 
> ```

You're supposed to remove the space, not keep it. You've always had a space, and that isn't right.

**Comment by yelnyafacee** [comment]
> o install -x github.com/caddyserver/xcaddy/cmd/xcaddy@latest

sadly I already tried it with or without spaces, and it still the same, mutiple 404 Not Found

**Comment by mholt** [comment]
@yelnyafacee We'll need to be able to reproduce the problem in order to be of assistance. So far, this looks like a local misconfiguration. It works for us, except in the case of extra spaces on the command... It's not even running any Caddy or Xcaddy code, so I don't think it's something we can fix... whatever it is.

**Comment by mohammed90** [comment]
After further experimentation, you most likely already have xcaddy cached build on your machine. This is evident by this line `# get https://proxy.golang.org/github.com/caddyserver/xcaddy/@v/list: 200 OK (0.317s)`. Run this command:

```
ls -al $(go env GOPATH)/bin | grep xcaddy
```

You should see positive results.

**Comment by yelnyafacee** [comment]
Have tested `go install -x github.com/caddyserver/xcaddy/cmd/xcaddy@latest` on anther server, still the same:

Server 1:
```
[root@vultrguest ~]# go install -x github.com/caddyserver/xcaddy/cmd/xcaddy@latest
# get https://proxy.golang.org/github.com/@v/list
# get https://proxy.golang.org/github.com/caddyserver/xcaddy/cmd/xcaddy/@v/list
# get https://proxy.golang.org/github.com/caddyserver/xcaddy/@v/list
# get https://proxy.golang.org/github.com/caddyserver/xcaddy/cmd/@v/list
# get https://proxy.golang.org/github.com/caddyserver/@v/list
# get https://proxy.golang.org/github.com/@v/list: 404 Not Found (0.276s)
# get https://proxy.golang.org/github.com/caddyserver/xcaddy/cmd/xcaddy/@v/list: 404 Not Found (0.282s)
# get https://proxy.golang.org/github.com/caddyserver/@v/list: 404 Not Found (0.299s)
# get https://proxy.golang.org/github.com/caddyserver/xcaddy/@v/list: 200 OK (0.306s)
# get https://proxy.golang.org/github.com/caddyserver/xcaddy/cmd/@v/list: 404 Not Found (0.309s)
```

Server 2:
```
[foodcrush@fcserver ~]$ go install -x github.com/caddyserver/xcaddy/cmd/xcaddy@latest
# get https://proxy.golang.org/github.com/@v/list
# get https://proxy.golang.org/github.com/caddyserver/@v/list
# get https://proxy.golang.org/github.com/caddyserver/xcaddy/cmd/@v/list
# get https://proxy.golang.org/github.com/caddyserver/xcaddy/cmd/xcaddy/@v/list
# get https://proxy.golang.org/github.com/caddyserver/xcaddy/@v/list
# get https://proxy.golang.org/github.com/@v/list: 404 Not Found (0.407s)
# get https://proxy.golang.org/github.com/caddyserver/xcaddy/@v/list: 200 OK (0.418s)
# get https://proxy.golang.org/github.com/caddyserver/@v/list: 404 Not Found (0.430s)
# get https://proxy.golang.org/github.com/caddyserver/xcaddy/cmd/@v/list: 404 Not Found (0.431s)
# get https://proxy.golang.org/github.com/caddyserver/xcaddy/cmd/xcaddy/@v/list: 404 Not Found (0.439s)
```
your package SUCKS

**Comment by mholt** [comment]
Yeahhh, that's a ban. Our faithful volunteer maintainers like Mohammed don't deserve abuse in any degree.
