### ISSUE TITLE
bug: fail to build with a forked module

### ISSUE THREAD

**Issue by tetra12** [caddyserver/xcaddy#126]
I forked a `caddy` module and ran a replace directive. Check [here](https://github.com/tetra12/caddy-grpc-web/blob/e9e90bec02a669b469bd3b030091c9becc9e16db/go.mod#L120) :eyes: .

I also had no errors in my code and ran `go mod tidy` to cleanup.

When I try to build a docker image, I'm getting this:
```docker
FROM caddy:builder-alpine AS builder

RUN xcaddy build \
  --with github.com/tetra12/caddy-grpc-web@test
```
I'm getting an error :roll_eyes: :
```bash
2022/12/11 13:53:15 [INFO] exec (timeout=0s): /usr/local/go/bin/go get -d -v github.com/tetra12/caddy-grpc-web@test github.com/caddyserver/caddy/v2@v2.6.2 
go: downloading github.com/tetra12/caddy-grpc-web v0.0.0-20221211134052-e9e90bec02a6
go: github.com/tetra12/caddy-grpc-web@v0.0.0-20221211134052-e9e90bec02a6: parsing go.mod:
        module declares its path as: github.com/mholt/caddy-grpc-web
                but was required as: github.com/tetra12/caddy-grpc-web

2022/12/11 13:53:19 [FATAL] exit status 1
```
The same happens when I put a commit hash like `github.com/tetra12/caddy-grpc-web@e9e90bec02a669b469bd3b030091c9becc9e16db`.

This seems like `xcaddy` doesn't pick up a replaced path of `github.com/tetra12/...` still calling for `github.com/mholt/...`

Any ideas :thinking:

**Comment by mholt** [comment]
I think xcaddy is working as expected, you can see it is trying to use the fork. But I believe forks still need to declare their module paths properly. I.e. changing the first line of go.mod. maybe I am wrong, I am mobile right now so I can't easily verify.

**Comment by mohammed90** [comment]
Typing this on the phone, so excuse the lark of exposition, but the command should be:

```
xcaddy build --with github.com/mholt/caddy-grpc-web= github.com/tetra12/caddy-grpc-web@master
```

**Comment by tetra12** [comment]
@mohammed90 I'd like to build from a feature branch. Is that possible?

When I fork from a module, I'd like to sync my master with the upstream master, but make test build with the feature branch.

**Comment by tetra12** [comment]
@mholt I'm not aware of a canonical way to work with go forks. Some thoughts are [here](https://stackoverflow.com/questions/14323872/using-forked-package-import-in-go) :eyes: 

The idea is the following:
1. Fork a module
2. Use `go mod edit -replace` to use either local disk or another git path
3. Test/try/integrate your module
4. Remove a `replace` line and make a PR

This way the module imports won't be affected in the code. But this seems to be confusing your `xcaddy` build flow :thinking:

**Comment by francislavoie** [comment]
Yes @tetra12, the `@master` part of the command @mohammed90 wrote _is_ the branch. Change that to whatever branch name you want. The important part is that the left side of the `=` is the original module name, and the right side is the actual location of the repo.

**Comment by tetra12** [comment]
@francislavoie  Hi thanks for your response. I think you didn't get the message in my report. Probably need to update it

Again
1. Original - `mholt` repo
2. Fork - `tetra12` repo
3. go.mod in fork **@master**: 
`module github.com/mholt/caddy-grpc-web`
4. go.mod in fork **@test**:
```replace
module github.com/mholt/caddy-grpc-web
replace github.com/mholt/caddy-grpc-web => github.com/tetra12/caddy-grpc-web v0.0.0-20221211131823-29c3405cc257
```

When I do `xcaddy build --with github.com/tetra12/caddy-grpc-web@test` it picks the `@master` branch and fails to compile due to invalid module path :crying_cat_face:

**Comment by mohammed90** [comment]
You're still missing the `<module>=<other-module>`.

**Comment by tetra12** [comment]
@mohammed90 hi could you pls give me an example ?

**Comment by francislavoie** [comment]
He did give an example!

**Comment by tetra12** [comment]
@mohammed90 @francislavoie ah, that example worked! Thanks for your help :handshake:
