### ISSUE TITLE
Can I write plug-ins for caddy in other programming languages? And compile the plug-in into bytecode or dynamic link libraries?

### ISSUE THREAD

**Issue by masx200** [caddyserver/xcaddy#135]
Can I write plug-ins for caddy in other programming languages? And compile the plug-in into bytecode or dynamic link libraries?

This allows the plug-in to be loaded and used at run time without recompiling the caddy source code.

**Comment by francislavoie** [comment]
No, we don't have a way to load in shared libraries currently. I'm not sure that's viable anyway.

The good news is you could likely write a simple plugin in Go that calls out to whatever program you write in another language.

**Comment by masx200** [comment]
https://github.com/bytecodealliance/wasmtime-go

https://github.com/wasmerio/wasmer-go
