### ISSUE TITLE
Module requirement issues during Docker builds

### ISSUE THREAD

**Issue by pmaene** [caddyserver/xcaddy#137]
I'm using `xcaddy`'s Docker image to build a Caddy image with the `caddy-dns/cloudflare` and `lucaslorentz/caddy-docker-proxy` plug-ins. However, I've been running into an issue where builds fail with `panic: internal error: can't find reason for requirement on ...`. When building from `2.6.4-builder`, it's failing on `github.com/google/pprof@v0.0.0-20210407192527-94a9f03dee38`, but earlier versions had issues with a requirement on a different module.

This occurs during CI runs on both GitHub Actions and private GitLab Runners, but I've also reproduced it locally just now. Thank you all for your work on Caddy, and I'm happy to provide any additional details you might need!

```Dockerfile
FROM caddy:2.6.4-builder AS builder

RUN xcaddy build \
    --with github.com/caddy-dns/cloudflare \
    --with github.com/lucaslorentz/caddy-docker-proxy/plugin/v2

FROM caddy:2.6.4

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

**Comment by francislavoie** [comment]
You're using the wrong import path for CDP. Use `github.com/lucaslorentz/caddy-docker-proxy/v2` instead.

**Comment by pmaene** [comment]
Oh, shoot! I had not noticed that change (though it is noted clearly in the repository) and did not realise this panic would have been related to a change like that. Thanks for pointing it out so quickly!
