### ISSUE TITLE
crypto/ecdh: package crypto/ecdh is not in GOROOT (/usr/local/go/src/crypto/ecdh)

### ISSUE THREAD

**Issue by dlfree-xzn-ir** [caddyserver/xcaddy#144]
```
Dockerfile:

FROM caddy:2.7-builder-alpine AS app_caddy_builder

RUN xcaddy build v2.6.4 \
	--with github.com/dunglas/mercure/caddy \
	--with github.com/dunglas/vulcain/caddy

```
##############
docker compose up -d:

[caddy app_caddy_builder 2/2] RUN xcaddy build v2.6.4  --with github.com/dunglas/mercure/caddy  --with github.com/dunglas/vul  114.8s

##############
error:

#0 777.9 github.com/dunglas/mercure/caddy imports
#0 777.9        github.com/caddyserver/caddy/v2/caddyconfig/httpcaddyfile imports
#0 777.9        github.com/caddyserver/caddy/v2/modules/caddytls imports
#0 777.9        github.com/smallstep/certificates/authority/provisioner imports
#0 777.9        github.com/slackhq/nebula/cert imports
#0 777.9        crypto/ecdh: package crypto/ecdh is not in GOROOT (/usr/local/go/src/crypto/ecdh)

failed to solve: process "/bin/sh -c xcaddy build v2.6.4 \t--with github.com/dunglas/mercure/caddy \t--with github.com/dunglas/vulcain/caddy" did not complete successfully: exit code: 1

**Comment by francislavoie** [comment]
See https://github.com/api-platform/api-platform/issues/2452
