### ISSUE TITLE
Building caddy times out on slower devices

### ISSUE THREAD

**Issue by nenad** [caddyserver/xcaddy#15]
Hey Matt, thanks a lot for creating `caddy`. I started playing with it today on my RPi and encountered an issue when building `caddy` with CloudFlare DNS module. Namely, the RPi took a little bit longer when building the project and after 5 minutes it timeout out when it was [fetching the deps](https://github.com/caddyserver/xcaddy/blob/master/environment.go#L229) and after I restarted the build it failed again after 5 minutes when [building the project](https://github.com/caddyserver/xcaddy/blob/master/builder.go#L94). I had to remove the timeout condition, rebuild `xcaddy` and then rerun it to finally get the modified `caddy` build.

I assume the timeout was added for CI builds but for development purposes it's really unexpected. I propose the timeout has a flag/option/env to be set and let the default behavior be without timing out. What do you think about this?

**Comment by mholt** [comment]
@nenad Please try with 1eaff74 - timeouts are now disabled when using the CLI (but can still be configured as a library).

**Comment by nenad** [comment]
@mholt Wow, that was a super fast response. Thanks a ton, the commit fixes the issue!
