### ISSUE TITLE
How to set timeouts?

### ISSUE THREAD

**Issue by qdm12** [caddyserver/xcaddy#16]
Hi there,

First of all many thanks for this tool, it's really useful!

I have a little problem when running it however on a slow machine (Github actions actually) where the context exceeds the timeout. Is there a way to set the timeout? It seems to come from [this context](https://github.com/caddyserver/xcaddy/blob/1eaff742dbcf4caa1a3bb7553de191d6e3d61f6d/environment.go#L184).

Thank you in advance.

**Comment by mholt** [comment]
Timeouts are actually disabled by default already in https://github.com/caddyserver/xcaddy/commit/1eaff742dbcf4caa1a3bb7553de191d6e3d61f6d. You can build from master to get it until there's a new release.
