### ISSUE TITLE
Getting errors when running command "xcaddy" on Debian 12

### ISSUE THREAD

**Issue by Oak-Trees** [caddyserver/xcaddy#166]
Hi, I'd like to start off with saying I have no idea what I'm doing.

I'm trying to use Xcaddy on my Raspberry Pi running Debian 12 Bookworm. I used apt-get to install both xcaddy and golang-go.

When I use the command "xcaddy" without anything extra I get the following error. Go can be accessed just fine.

go: cannot match "all": go.mod file not found in current directory or any parent directory; see 'go help modules'
2024/01/04 22:01:45 [ERROR] exec [go list -mod=readonly -m -json all]: exit status 1:

When I run "xcaddy list-modules" for example I get the same error. I tried it with and without using sudo.

**Comment by francislavoie** [comment]
What Go version do you have installed? Make sure you have at least Go 1.20

**Comment by emilylange** [comment]
What are you trying to do?

`xcaddy` has essentially two modes:
1. `xcaddy build`: build a custom caddy binary (with/without plugins or the newly added `--embed`)
1. `xcaddy <anything else>`: a `go run` wrapper if you hack on Caddy itself (or a plugin), which requires a project structure in your local directory

Unfortunately, invoking `xcaddy` with no parameter errors out with that rather unhelpful error message you shared.
This is probably something that could be improved but oh well /shrug

If you just want to make sure your `xcaddy` setup (with go) works by giving it a test run, try `xcaddy build`.
This will build and output a custom "vanilla" (no plugins, no embeds) caddy binary in your local directory.

If you just want to make sure `xcaddy` is working (but without invoking/validating your go toolchain), try `xcaddy version`.

Please refer to the _Command usage_ section in the README.md: https://github.com/caddyserver/xcaddy#command-usage

**Comment by francislavoie** [comment]
Yeah just install Go manually (basically just unzip it somewhere, that's all) https://go.dev/doc/install

**Comment by Oak-Trees** [comment]
> What are you trying to do?
> 
> `xcaddy` has essentially two modes:
> 
>     1. `xcaddy build`: build a custom caddy binary (with/without plugins or the newly added `--embed`)
> 
>     2. `xcaddy <anything else>`: a `go run` wrapper if you hack on Caddy itself (or a plugin), which requires a project structure in your local directory
> 
> 
> Unfortunately, invoking `xcaddy` with no parameter errors out with that rather unhelpful error message you shared. This is probably something that could be improved but oh well /shrug
> 
> If you just want to make sure your `xcaddy` setup (with go) works by giving it a test run, try `xcaddy build`. This will build and output a custom "vanilla" (no plugins, no embeds) caddy binary in your local directory.
> 
> If you just want to make sure `xcaddy` is working (but without invoking/validating your go toolchain), try `xcaddy version`.
> 
> Please refer to the _Command usage_ section in the README.md: https://github.com/caddyserver/xcaddy#command-usage

I'm just trying to build Caddy with plugins. Ah, xcaddy build gives an error [FATAL] exit status 1. Probably because Go is too old, I'll try again when I have a newer Go installed.

**Comment by Oak-Trees** [comment]
The latest version of Go fixed it. It works great now. Thank you both for your help.
