### ISSUE TITLE
How to get my self-written module included in the Standard features of https://caddyserver.com/download?

### ISSUE THREAD

**Issue by leaker** [caddyserver/xcaddy#169]
I've created a plugin that automatically trusted_proxies from `AWS CloudFront EDGE servers`:
https://github.com/xcaddyplugins/caddy-trusted-cloudfront

# trusted_proxies cloudfront module for `Caddy`

The module auto trusted_proxies `AWS CloudFront EDGE servers` from https://d7uri8nf7uskq.cloudfront.net/tools/list-cloudfront-ips

## Requirements

- [Go installed](https://golang.org/doc/install)
- [xcaddy](https://github.com/caddyserver/xcaddy)

## Build

```bash
$ xcaddy build --with github.com/xcaddyplugins/caddy-trusted-cloudfront
```

## `Caddyfile` Syntax

```caddyfile
trusted_proxies cloudfront {
    interval <duration>
}
```

- `interval` How often to fetch the latest IP list. format is [caddy.Duration](https://caddyserver.com/docs/conventions#durations). For example `12h` represents **12 hours**, and "1d" represents **one day**. default value `1d`.

## `Caddyfile` Example

```caddyfile
trusted_proxies cloudfront {
    interval 1d
}
```

**Comment by mohammed90** [comment]
You register/login on the [website](https://caddyserver.com) by clicking on [Account](https://caddyserver.com/account/). Once you're logged in, you'll find a `Register Package` button.
