### ISSUE TITLE
Build Caddy statically without CGO

### ISSUE THREAD

**Issue by qdm12** [caddyserver/xcaddy#17]
Hello,

When trying to build Caddy statically (with `CGO_ENABLED=0` and without `gcc`), using:

```sh
docker run -it --rm -w /tmp/caddy golang:1.14-alpine3.11
apk add git
export CGO_ENABLED=0
export GO111MODULE=on
go get github.com/caddyserver/xcaddy/cmd/xcaddy@master
xcaddy build v2.0.0
```

I obtain the errors:

```
2020/05/22 13:55:03 [INFO] Temporary folder: /tmp/buildenv_2020-05-22-1355.280615980
2020/05/22 13:55:03 [INFO] Writing main module: /tmp/buildenv_2020-05-22-1355.280615980/main.go
2020/05/22 13:55:03 [INFO] Initializing Go module
2020/05/22 13:55:03 [INFO] exec (timeout=10s): /usr/local/go/bin/go mod init caddy
go: creating new go.mod: module caddy
2020/05/22 13:55:03 [INFO] Pinning versions
2020/05/22 13:55:03 [INFO] exec (timeout=0s): /usr/local/go/bin/go get -d -v github.com/caddyserver/caddy/v2@v2.0.0 
2020/05/22 13:55:04 [INFO] Build environment ready
2020/05/22 13:55:04 [INFO] Building Caddy
2020/05/22 13:55:04 [INFO] exec (timeout=0s): /usr/local/go/bin/go build -o /tmp/caddy/caddy -ldflags -w -s -trimpath 
# runtime/cgo
exec: "gcc": executable file not found in $PATH
2020/05/22 13:55:04 [INFO] Cleaning up temporary folder: /tmp/buildenv_2020-05-22-1355.280615980
2020/05/22 13:55:04 [FATAL] exit status 2
```

Any idea how I can solve that? Or is this related to xcaddy? Or one of the dependencies?

Thanks!

**Comment by mholt** [comment]
Looks like it's not actually being disabled, try doing the same thing without Docker. Sorry though, I don't use Docker so I don't know how to help. Try asking on our forums instead. If this is a bug in xcaddy we can reopen this though.

**Comment by qdm12** [comment]
This is definitely not related to Docker though.

Can you try on your machine:

```sh
CGO_ENABLED=0 xcaddy build v2.0.0
ldd caddy
```

To see if it's actually built statically? Thanks!

**Comment by mholt** [comment]
@qdm12 What is the output for you? (I don't have ldd on my Mac so I need to find a workaround in the meantime.)

**Comment by qdm12** [comment]
Maybe try on osx:

```sh
otool -L caddy
```

I can compile it if I have gcc installed (even with CGO_ENABLED=0). Running `ldd caddy` on it gives me the corresponding C library (on alpine it's musl).

Note that compiling Go programs (and caddy 1.0.x) statically works apart from that so my guess is it has something to do with xcaddy :thinking:

I will try building Caddy 2 statically without xcaddy to make sure it's on xcaddy's side.

**Comment by mholt** [comment]
@qdm12 Thanks for the tip, that made it pretty quick. Try the latest from master if you please?

**Comment by qdm12** [comment]
Yep it works! Thanks!! 👍

**Comment by mholt** [comment]
@qdm12 You can see the fix in https://github.com/caddyserver/xcaddy/commit/a1e17ca9b98a2b0915a55091b97a8ad1b942279b - I wasn't converting from true/false to 1/0.
