### ISSUE TITLE
Error when trying to build Caddy crypto/ecdh: package crypto/ecdh is not in GOROOT (/usr/lib/go-1.18/src/crypto/ecdh)

### ISSUE THREAD

**Issue by mrkhdev** [caddyserver/xcaddy#171]
I have downloaded the binaries of the latest release of xcaddy and I'm trying to build xcaddy with a dns module for namecheap. 

I'm getting the error:

![image](https://github.com/caddyserver/xcaddy/assets/125406055/a6d4fad3-8069-44b1-b076-59f21b5c828e)

Even when I build caddy without modules I get the error. I tried to set the CADDY_VERSION to an earlier one, but that didn't work. I'm using WSL on Windows and go version go1.18.1 linux/amd64.

**Comment by mholt** [comment]
Caddy requires at least the latest two versions of Go. Version 1.18 is too old at this point.

**Comment by mrkhdev** [comment]
> Caddy requires at least the latest two versions of Go. Version 1.18 is too old at this point.

That worked for me. Thanks!

**Comment by mrkhdev** [comment]
Resolved
