### ISSUE TITLE
xcaddy v0.3.5 vs v0.4.0 = 15mb increase in filesize on windows

### ISSUE THREAD

**Issue by wazerstar** [caddyserver/xcaddy#181]
What caused such huge amount of increased file size, I'm mean caddy is already beautiful small in size for what it can achieve.

But was just wondering..

![RHXOhzt](https://github.com/caddyserver/xcaddy/assets/4474519/f57bad87-f9ca-464d-a1d3-13c11bc3fe62)

**Comment by mholt** [comment]
Is this the exact same version of Caddy and Go? (What is the output of `caddy build-info` for both binaries?) The _only_ difference is the version of `xcaddy` used to build it?

**Comment by mohammed90** [comment]
For the record, the size of the [CI artifact](https://github.com/caddyserver/caddy/actions/runs/8916578792) of Caddy at commit https://github.com/caddyserver/caddy/commit/7e2510ef43d3439c682d56b580e4013a0cc9cc3e is 41.1MB. I doubt the xcaddy version changes anything, unless you're using the `--embed` feature. But, yes, we need more details.

**Comment by wazerstar** [comment]
> Is this the exact same version of Caddy and Go? (What is the output of `caddy build-info` for both binaries?) The _only_ difference is the version of `xcaddy` used to build it?




> For the record, the size of the [CI artifact](https://github.com/caddyserver/caddy/actions/runs/8916578792) of Caddy at commit [caddyserver/caddy@7e2510e](https://github.com/caddyserver/caddy/commit/7e2510ef43d3439c682d56b580e4013a0cc9cc3e) is 41.1MB. I doubt the xcaddy version changes anything, unless you're using the `--embed` feature. But, yes, we need more details.


Both version 

![TM31QfL](https://github.com/caddyserver/xcaddy/assets/4474519/f2122cbd-d28e-4c0c-b1b9-1b840cfd925d)

**Comment by mholt** [comment]
How can we reproduce the size difference?

**Comment by wazerstar** [comment]
I see a difference here

![yLozVrT](https://github.com/caddyserver/xcaddy/assets/4474519/1f58bb5f-b36c-4c2c-9268-16f49c02a3c3)

also I see -trimpath=true  cmd missing in 0.4.0 and replaced on same line with -tags=nobadger, 

![wc4Z1u8](https://github.com/caddyserver/xcaddy/assets/4474519/ae314aea-8719-4e28-904b-2ca51e946cd3)

**Comment by mholt** [comment]
Ah! Of course. :) Thanks for the quick fix!

**Comment by wazerstar** [comment]
> Found the culprit. I added this line here:
> 
> https://github.com/caddyserver/xcaddy/blob/f99151eee93013f77053d29c62e9da4ad3eb5738/environment.go#L130
> 
> which tripped this check here:
> 
> https://github.com/caddyserver/xcaddy/blob/f99151eee93013f77053d29c62e9da4ad3eb5738/builder.go#L130-L135
> 
> so now debug symbols are not removed and the paths are not trimmed.
> 
> One sec...

hotfix issue

https://github.com/caddyserver/xcaddy/actions/runs/8971616569?pr=182

```
2024/05/06 17:27:13 [INFO] exec (timeout=0s): C:\Program Files\Go\bin\go.exe mod tidy -e
2024/05/06 17:27:14 [INFO] exec (timeout=0s): C:\Program Files\Go\bin\go.exe build -o C:\Users\Denni\Desktop\xcaddy\caddy.exe -ldflags -w -s -trimpath -tags nobadger
flag provided but not defined: -tags nobadger
usage: go build [-o output] [build flags] [packages]
Run 'go help build' for details.
2024/05/06 17:27:15 [INFO] Cleaning up temporary folder: C:\Users\Denni\AppData\Local\Temp\buildenv_2024-05-06-1726.2852208866
2024/05/06 17:27:15 [FATAL] exit status 2
```
