### ISSUE TITLE
[FATAL] exit status 1

### ISSUE THREAD

**Issue by Hor1kon** [caddyserver/xcaddy#193]
I have seen other people facing this issue and everywhere the answer was an old verison of go, but I have installed 1.22.5 linux/adm64 one (I think this is the newest one), but still face this issue

![Screenshot_58](https://github.com/caddyserver/xcaddy/assets/113005159/1ddd5b9a-8247-4b88-8af4-8f9e7f0a5b9c)

Thanks for your future answer and great job on caddy!

*I am not a professional developer, so if I did something stupid, sorry)

**Comment by mholt** [comment]
Looks like the Go module proxy is malfunctioning or is being blocked by a proxy/firewall. Unfortunately not a problem we can fix for you.

**Comment by Hor1kon** [comment]
I found out the origin of the problem. I was russian server, that was unable to get some packages. Same problem appears with Cyprus and some other countries. I got other server and now try to understand how does it work, because it is much different from default caddy) thx for lightening the right route @mholt

**Comment by mholt** [comment]
Makes sense, thanks for following up!

**Comment by Hor1kon** [comment]
> Makes sense, thanks for following up!

by the way, I have decided to install xcaddy to install your rate-limit package, it is very easy to use and works great, thx!

**Comment by mholt** [comment]
Awesome! Glad to hear it :)
