### ISSUE TITLE
How can I update caddy server with modules ?

### ISSUE THREAD

**Issue by kyesil** [caddyserver/xcaddy#194]
Hi 
I install caddy and xcaddy with apt. 
I added cludflare module with xcaddy.
I think caddy rebuild and create new binary. 

Apt update & upgrade  update my caddy server ?

**Comment by francislavoie** [comment]
Follow these instructions: https://caddyserver.com/docs/build#package-support-files-for-custom-builds-for-debianubunturaspbian

**Comment by alexander-potemkin** [comment]
I'm sorry, I know it's a closed issue, but I guess it's the best place to ask: would it be possible to somehow automate caddy server rebuild and reinstall, once a new server or plugin version appears?

If that's definitely outside of scope or way, way ahead in the backlog, any shell script hints would be much appreciated!

**Comment by francislavoie** [comment]
I don't recommend unattended upgrades, to be honest. It's best if you do it regularly, while at the terminal, to validate that your config isn't subject to breaking changes.

**Comment by alexander-potemkin** [comment]
I know, thanks! No reason to do it manually on non-production servers though… :)

**Comment by alexander-potemkin** [comment]
> We feel it's best for upgrades to at least be somewhat intentional.
> 
> Also, Caddy doesn't have a 100% compatibility guarantee, and we can't control anything like that with third party plugins. You should only run plugins you trust, and have reviewed release notes for.

@mholt , thank you - I do know what you are speaking about, but there are cases when it will be just fine: non-production systems that triggers automatic updates via cron at non-use hours or automated tests.

I hear however you that it’s not a goal and unlikely to be implemented any time soon, that’s fine - thanks for letting me know :)
