### ISSUE TITLE
Add option to disable version check after build

### ISSUE THREAD

**Issue by lucaslorentz** [caddyserver/xcaddy#20]
Readme indicates that GOOS, GOARCH, and GOARM can be set, probably for cross-compilation scenarios.

But at the end of the build, there is a check that tries to execute the build output: https://github.com/caddyserver/xcaddy/blob/master/cmd/xcaddy/main.go#L131

Which might be incompatible with current architecture when doing cross-compilation.
For example, I'm on Linux building Caddy for Windows, or I'm on amd64 building for ARM.

I would like to suggest either removing the check, or having a parameter to disable it.

**Comment by lucaslorentz** [comment]
Related to https://github.com/lucaslorentz/caddy-docker-proxy/issues/141

**Comment by mholt** [comment]
The check is not important, just a convenience for the user. Is it causing actual harm? You can just ignore it.

**Comment by lucaslorentz** [comment]
I had the impression xcaddy was failing the build, returning an exit code different than 0. If that's not the case. I will just ignore the visual output and we can close this issue.

**Comment by mholt** [comment]
Ah, in that case, there's a simple fix -- we can just do the check if it wasn't a cross-compile. Then your exit status won't get tainted.

**Comment by lucaslorentz** [comment]
It worked! Thanks
