### ISSUE TITLE
`--embed` with no alias drops the parent directory from the embedded files

### ISSUE THREAD

**Issue by camhux** [caddyserver/xcaddy#202]
When `xcaddy` is invoked with an `--embed` target without an alias, referring to a directory within the working directory, like so:
```
$ xcaddy --embed my-dir
```
…this results in the `files/` directory of Caddy's embedded FS containing the _contents_ of `my-dir/`, as though `my-dir/*` were the target, rather than a `files/my-dir/` directory containing the contents of `my-dir`.

This behavior was unexpected for me because it diverges from the way that the `go:embed` directive of the Go tool treats its path arguments. Go will embed a specified directory (without a glob suffix) as a directory, and any specified subdirectories will preserve the entire directory structure that leads to that subdirectory. I.e., `go:embed my-dir` creates an embedded directory `my-dir`, and `go:embed dir-a/dir-b` creates an embedded directory structure of `dir-a/dir-b`.

This behavior results from this line:
https://github.com/caddyserver/xcaddy/blob/b72e330d5d7439ce848e29ade848760012e9e386/environment.go#L96
where `d.Name` is empty if there was no alias in the corresponding argument to `--embed`.

---

I see how this could be the intended design for `--embed`, and I also realize that the argument to `--embed` must **not** be treated identically as the arguments to a `go:embed` directive, since relative path elements like `..` are permitted in `--embed` arguments for greater flexibility. If this is the case, I think this behavior should be specified in the `--embed` documentation.

If it's _not_ the intended design, I suggest that an unaliased path passed to `--embed` that points to a directory should use the _last_ directory name as the copy target when creating the entry in the embedded `files/` dir. I.e., `--embed ../other-dir/my-dir` -> `files/my-dir`.

Either way, I'm happy to submit the patch. (I've been tinkering with `--embed` on a fork already.)

Thanks!

**Comment by mohammed90** [comment]
The logic is a carryover from Matthew's prototype module https://github.com/mholt/caddy-embed. He lays out the reasoning for that part in the README under the Site Root section.

**Comment by mholt** [comment]
Hmm, yeah, I think the reason for this is to make it so that URI paths don't _have_ to contain a subfolder. The problem is that without the way we do it, you _have_ to have a subfolder like `/files/...` in your URI, whereas with the way we do it, you _may_ have a subfolder if you want, by naming it anything you like, within the source folder. Does that make sense?

I mean, if this is truly a problem I am open to changing things, I just figured people would want the option to choose whether a subfolder was required or not.

**Comment by mholt** [comment]
Yes a simple PR would be accepted! Thank you!

**Comment by camhux** [comment]
Did wordsmithing here: https://github.com/caddyserver/xcaddy/pull/206. Whether or not the PR goes in, I consider this issue resolved. Thanks!
