### ISSUE TITLE
`--embed` usage example seems incomplete

### ISSUE THREAD

**Issue by camhux** [caddyserver/xcaddy#203]
In the documentation for `--embed`, the example [Caddyfile](https://github.com/caddyserver/xcaddy/blob/b72e330d5d7439ce848e29ade848760012e9e386/README.md?plain=1#L124-L136) uses `fs embedded` directives as though the `embedded` filesystem is pre-declared.

In my own testing, I found that `xcaddy` had rather created a submodule of `caddy.fs` named `embedded`, which meant I still had to declare a filesystem in the global options block to be able to serve files from the embedded FS, which in the example would look like this:

```
{
	filesystem embedded embedded
}

foo.localhost {
	root * /foo
	file_server {
		fs embedded
	}
}

bar.localhost {
	root * /bar
	file_server {
		fs embedded
	}
}
```

Without this instantiation in the global options block, the debug output from the server would warn about attempts to use an undeclared filesystem.

I'm pretty new to Caddy and `xcaddy`, so I'm curious if there's something I've missed about how this sample usage is supposed to work, or if this is a case where the example should be updated for completeness.

**Comment by mohammed90** [comment]
Good catch! The virtual filesystem feature of Caddy changed in v2.8.0, and the documentation here was missed.

**Comment by camhux** [comment]
Always happy to bring fresh eyes 😃 Updated the example here: https://github.com/caddyserver/xcaddy/pull/204
