### ISSUE TITLE
Next steps and production aspirations

### ISSUE THREAD

**Issue by ekrtf** [caddyserver/xcaddy#21]
Hello!

Great tool! Extending caddy has tremendous value for my use case.

I'm discovering caddy and xcaddy so I'm having a hard time picturing how much work is left to make it ready? Are you looking for contributors? How risky would it be for me to use it in production now?

Many thanks for your great work on this!

**Comment by mholt** [comment]
Hi, thanks for the feedback!

Not really sure what you're asking -- many of us have been using xcaddy for months just fine. And Caddy has been used in production for several years now!

Are you volunteering to contribute? Are you talking about Caddy or xcaddy?

**Comment by ekrtf** [comment]
Thanks for your quick response. I guess I'm just trying to figure out if writing my own caddy http handler is something that is somewhat battle tested?

To do so, I'll have to:
1. write the http handler, `ServeHTTP` in the [example](https://caddyserver.com/docs/extending-caddy#complete-example)
2. compile my own caddy binary using `xcaddy build --with X`
3. run caddy and be happy

Is that the correct approach? Is there a way to "just" import an external module? In the Caddyfile maybe?

**Comment by mholt** [comment]
@ekrtf Close, but not quite. Read this part of the docs: https://github.com/caddyserver/xcaddy#for-plugin-development
