### ISSUE TITLE
Prefetching go modules etc.

### ISSUE THREAD

**Issue by erikschul** [caddyserver/xcaddy#211]
`xcaddy build` does a lot of downloading, which isn't related to building.
Is it possible to fetch these in a separate step, like `xcaddy install` or something, so that this step can be cached independently in CICD?
Then running `xcaddy build --with` could do the equivalent of `git pull` / download additional files that are relevant for a new build.

**Comment by erikschul** [comment]
```
go mod init caddy
go get -d -v github.com/caddyserver/caddy/v2@master
```

**Comment by mholt** [comment]
`xcaddy build` just wraps `go build` -- it downloads if it has to.

**Comment by francislavoie** [comment]
Can't you just do `xcaddy build` as normal then cache the GOMODCACHE and GOCACHE locations? If you're using github actions, the https://github.com/actions/setup-go action does this for you already.
