### ISSUE TITLE
add --version flag on cli for xcaddy itself

### ISSUE THREAD

**Issue by dkebler** [caddyserver/xcaddy#22]
so I can easier tell what version of xcaddy I am running can you please add a --version flag.  I mean the version of xcaddy not caddy2.

`xcaddy --version`

Even better if it doesn't impact (i.e. <1000ms) compile time have it always check and report if it needs to update and offer to `go get -u` right there.

**Comment by Henrocker** [comment]
Funny, today I tried the same thing :D Would be great to have this flag!

```
hnrk@host1:~$ xcaddy --version
go list -m: not using modules
2021/02/19 10:11:41 [ERROR] exec [go list -m]: exit status 1:
hnrk@host1:~$ xcaddy version
go list -m: not using modules
2021/02/19 10:11:48 [ERROR] exec [go list -m]: exit status 1:
```

Makes it easier to see if there's already a newer version available that fixed bugs in currently installed version.
