### ISSUE TITLE
How to build caddy from a different branch/repository?

### ISSUE THREAD

**Issue by rgl** [caddyserver/xcaddy#24]
How can we build caddy from a different branch/repository?

We can specify a `CADDY_VERSION` environment variable, but the module path seems to be hardcoded at:

* https://github.com/caddyserver/xcaddy/blob/1d18c5862c1f4d81cf69ee821584ab804ab27b09/builder.go#L232
* https://github.com/caddyserver/xcaddy/blob/1d18c5862c1f4d81cf69ee821584ab804ab27b09/environment.go#L33

Is there a way to override that module path? or somehow override `go get` to fetch that module from somewhere else?

**Comment by mafrosis** [comment]
I was just digging around to see how to feed a local path in. I'd like to build caddy from source at `./caddy`, but including a plugin

**Comment by rgl** [comment]
I figured it out. This can be done with:

```bash
git clone https://github.com/caddyserver/caddy.git my-caddy-fork
./xcaddy build --with github.com/caddyserver/caddy/v2=$PWD/my-caddy-fork
```

**Comment by mholt** [comment]
Ah, you beat me to it. Yep, using `=` in a `--with` argument will create a `replace` directive in the `go.mod` file.
