### ISSUE TITLE
Publish xcaddy builds for armv7

### ISSUE THREAD

**Issue by mafrosis** [caddyserver/xcaddy#25]
Without a handy package we can pull for building `caddy` on ARM, to build caddy I have to:

1. Pull xcaddy code
2. Build xcaddy
3. Use xcaddy to build caddy

... Which seems a bit over the top ;) 

The other option is to not use xcaddy at all - which might be a better option?

**Comment by mafrosis** [comment]
A simple workaround using Docker:

```
FROM golang:1.14-alpine as builder
RUN go get -u github.com/caddyserver/xcaddy/cmd/xcaddy
```

**Comment by Mohammed90** [comment]
You're in luck! The release that includes the binaries for all kinds of arches has been sitting as `draft` for 15 days waiting to be published 😅 
@mholt, should we change `draft: true` to `false` to enable immediate publishing of releases on this repo?
https://github.com/caddyserver/xcaddy/blob/e11b1988bd7e1d474db024a1a9a44940b95a3f4b/.goreleaser.yml#L64

**Comment by mholt** [comment]
@Mohammed90 Sure! If that works, might as well.
