### ISSUE TITLE
can we have a Docker Hub image?

### ISSUE THREAD

**Issue by SvenDowideit** [caddyserver/xcaddy#29]
I'm finally starting to play with the acme modules, and to get started, am using the following Dockerfile (with all sorts of extra bits to help me).

The main not-so-good thing, is that i'm guessing what version of go I should use, and then will have to update it

```
# docker build --target xcaddy --tag xcaddy .
FROM golang:1.14 as xcaddy

# get xcaddy
RUN go get -u github.com/caddyserver/xcaddy/cmd/xcaddy

# docker build --target dnsgandibuild --tag dnsgandibuild .
FROM xcaddy as dnsgandibuild
# https://caddy.community/t/how-to-use-dns-provider-modules-in-caddy-2/8148
RUN xcaddy build --with github.com/caddy-dns/gandi


# docker build --target dnsgandi --tag dnsgandi .
FROM caddy as dnsgandi
COPY --from=dnsgandibuild /go/caddy /usr/bin/caddy

ENV GANDIV5_API_KEY=
RUN echo "loc.alho.st {" > /etc/caddy/Caddyfile \
    && echo 'respond "Hello, world!"' >> /etc/caddy/Caddyfile \
    && echo "tls {" >> /etc/caddy/Caddyfile \
    && echo "dns gandi {env.GANDIV5_API_KEY}" >> /etc/caddy/Caddyfile \
    && echo "}" >> /etc/caddy/Caddyfile \
    && echo "}" >> /etc/caddy/Caddyfile
```

instead, I'd like to just use the correct go, with the correct caddy - all setup by "the caddy people" :)

```
FROM caddyserver/xcaddy as build
RUN xcaddy build --with github.com/caddy-dns/gandi

FROM caddy
COPY --from=build /go/caddy /usr/bin/caddy
```

Happy to make a PR with Dockerfile and .github action that looks like https://github.com/SvenDowideit/ruuvi-prometheus/blob/master/.github/workflows/dockerpublish.yml

**Comment by francislavoie** [comment]
Yes it's definitely planned, but we haven't spent the time on it yet. @hairyhenderson is on vacation right now but I'll work with him when he's back to get that done sooner rather than later 👍

**Comment by SvenDowideit** [comment]
na - the above Dockerfile is easier - as i don't need to install anything :).

wrt Docker guru... yeah, well, I may have written many of the docs you've read - while i worked for Docker :D

**Comment by francislavoie** [comment]
> na - the above Dockerfile is easier - as i don't need to install anything :).

I don't see what you mean, you don't need to install anything with the other one either.

**Comment by SvenDowideit** [comment]
yup - 

> aha, caddy builder - basically same ux :)

the thing that throws me, is in most places, the docs talk about running xcaddy

**Comment by francislavoie** [comment]
Yeah, because the docs don't make the assumption that you're using Docker. If you're using Docker, read the Docker documentation. If you're not, then `xcaddy` is the best option available (and it's what backs the `/download` page of the Caddy website).

**Comment by hairyhenderson** [comment]
Oh! Hey @SvenDowideit 👋

Sorry for the late response - I was on vacation ⛺

The [caddy-builder.sh](https://github.com/caddyserver/caddy-docker/blob/master/2.1/builder/caddy-builder.sh) script pre-dates `xcaddy` (but only by a few weeks if memory serves), which is why there are two different ways to build Caddy.

I've opened https://github.com/caddyserver/caddy-docker/issues/107 to fix this.

@SvenDowideit if that all makes sense, do you want to close this and move any extra conversation over to the `caddy-docker` issue?

**Comment by mholt** [comment]
Looks like this is taken care of! :+1:
