### ISSUE TITLE
Output Binary is Not working

### ISSUE THREAD

**Issue by TheLazyLemur** [caddyserver/xcaddy#35]
## Issue

I am using the command :
```bash
xcaddy build
```
The build is successful, but the out put binary outputs:
```
panic: qtls.ClientSessionState not compatible with tls.ClientSessionState

goroutine 1 [running]:
github.com/lucas-clemente/quic-go/internal/handshake.init.2()
	github.com/lucas-clemente/quic-go@v0.17.1/internal/handshake/unsafe.go:26 +0x205
```

Is there something im doing wrong? The binaries downloaded from the website work fine.

## Some Extra Info
```
OS : Ubuntu 20.04
Go Version: go version go1.15.2 linux/amd6 (Snap Pack)
```

**Comment by Mohammed90** [comment]
This is a known issue in building Caddy with Go 1.15 and been fixed in master. Build Caddy from master using:
`xcaddy build master`
