### ISSUE TITLE
-bash: xcaddy: command not found

### ISSUE THREAD

**Issue by Ninzero** [caddyserver/xcaddy#5]
Hi,

I hope this is not a terrible question, I did try my best to solve the problem, but it just doesn't work.

I first installed go 1.14.2 following this page: [Getting Started](https://golang.org/doc/install). I did remember to add  `/usr/local/go/bin` to `$PATH`. Everything was fine and this [test](https://golang.org/doc/install#testing) succeeded.

Then I set `$GO111MODULE` to on. And I ran `go get -u github.com/caddyserver/xcaddy/cmd/xcaddy` as instructed. I tried to run this command almost everywhere: my home directory, I cloned caddy and run this command. But whatever I do, there is no such command called xcaddy.

**Comment by mholt** [comment]
`go get` will install the binary into your `$GOPATH/bin`, which is different from `/usr/local/go/bin`. It doesn't seem to be very well-documented anymore, unfortunately. If you add that path to your PATH then it should work. Look in `$HOME/go/bin` for the xcaddy binary.

(Closing, but feel free to reopen if this turns out to be an issue with our repo!)

**Comment by ghhk** [comment]
I get that error too! When I use `cd /root/go/bin` I see a file named xcaddy. But when I run any command about xcaddy it give me an error like "-bash: xcaddy: command not found"

**Comment by MrChadMWood** [comment]
@ghhk Did you try step 4?

>$GOPATH/bin, which is different from /usr/local/go/bin

1. Uninstall old and get new GO
`rm -rf /usr/local/go && tar -C /usr/local -xzf go1.21.5.linux-amd64.tar.gz`

2. Add to PATH
`export PATH=$PATH:/usr/local/go/bin`

3. Install xcaddy
`go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest`

4. **Add GO package directory to PATH**
`export PATH=$PATH:$GOPATH/bin`

5. Build caddy as desired
`xcaddy build --with github.com/caddy-dns/route53`
