### ISSUE TITLE
Can't do module replacement with github forks

### ISSUE THREAD

**Issue by francislavoie** [caddyserver/xcaddy#50]
So I want to have a replacement like:

```
replace github.com/mholt/caddy-dynamicdns => github.com/francislavoie/caddy-dynamicdns caddyfile
```

So I try this:

```
xcaddy build --with github.com/mholt/caddy-dynamicdns=github.com/francislavoie/caddy-dynamicdns@caddyfile
```

But it does this:

```
...
2021/02/21 07:25:03 [INFO] exec (timeout=0s): /usr/local/go/bin/go get -d -v github.com/mholt/caddy-dynamicdns=github.com/francislavoie/caddy-dynamicdns@caddyfile
go get github.com/mholt/caddy-dynamicdns=github.com/francislavoie/caddy-dynamicdns@caddyfile: malformed module path "github.com/mholt/caddy-dynamicdns=github.com/francislavoie/caddy-dynamicdns": invalid char '='
```

This obviously isn't quite right, cause it never did the `go mod edit -replace`.

Next I tried without `@caddyfile` (my branch), and I get this:

```
2021/02/21 07:29:24 [INFO] Resolved relative replacement github.com/mholt/caddy-dynamicdns=github.com/francislavoie/caddy-dynamicdns to /root/github.com/francislavoie/caddy-dynamicdns
...
2021/02/21 07:29:24 [INFO] Replace github.com/mholt/caddy-dynamicdns => /root/github.com/francislavoie/caddy-dynamicdns
2021/02/21 07:29:24 [INFO] exec (timeout=10s): /usr/local/go/bin/go mod edit -replace github.com/mholt/caddy-dynamicdns=/root/github.com/francislavoie/caddy-dynamicdns
...
caddy imports
        github.com/mholt/caddy-dynamicdns: github.com/mholt/caddy-dynamicdns@v0.0.0-00010101000000-000000000000: replacement directory /root/github.com/francislavoie/caddy-dynamicdns does not exist
```

So `xcaddy` thinks that path is relative but it's not, it's a git repo.

I think to detect if it's relative, we should look if there's a `.` in front, so if you want to refer to something in the current dir then you do `./blah` in the replacement. That should allow github module paths to work.

The workaround obviously for now is to `git clone` the relevant repo then use a relative path on that, but it would be nice so that people can easily test branches/PRs for plugins without cloning.

**Comment by mholt** [comment]
Hmm, wouldn't you just change the `require` dependency from `github.com/mholt/caddy-dynamicdns` to `github.com/francislavoie/caddy-dynamicdns`?

**Comment by francislavoie** [comment]
No because that would imply the master branch, but if it's not on the master branch that won't work.

**Comment by mholt** [comment]
Set the version of that require directive to another branch then?

**Comment by francislavoie** [comment]
What do you mean?

**Comment by mholt** [comment]
`require` directives consist of a module name and a version:

```
github.com/mholt/acmez v0.1.3
```

so instead of a version on the master branch, choose a different branch name.

**Comment by francislavoie** [comment]
Right but you would do that with `@` in the `xcaddy` command, but that doesn't work. Did you miss that in the post above?

**Comment by mholt** [comment]
I mean do this instead:

```
xcaddy build --with github.com/francislavoie/caddy-dynamicdns@caddyfile
```

**Comment by francislavoie** [comment]
That won't work because the `module` in that repo is `github.com/mholt/caddy-dynamicdns` so a `replace` needs to happen.

**Comment by mholt** [comment]
Oh... I see... how does the `go` tool determine which kind of replacement to do, I wonder? (Can look into it later)

**Comment by francislavoie** [comment]
It does it just fine if you specify `go mod edit -replace github.com/mholt/caddy-dynamicdns=/root/github.com/francislavoie/caddy-dynamicdns@caddyfile` but the problem is our "relative path" resolve step breaks it.

**Comment by Mohammed90** [comment]
FWIW, I started working on it last night but didn't finish it. This is where I'm at now.

Diff:

```diff
diff --git a/cmd/xcaddy/main.go b/cmd/xcaddy/main.go
index 001f462..39d8b72 100644
--- a/cmd/xcaddy/main.go
+++ b/cmd/xcaddy/main.go
@@ -76,7 +76,7 @@ func runBuild(ctx context.Context, args []string) error {
 			})
 			if repl != "" {
 				// adjust relative replacements in current working directory since our temporary module is in a different directory
-				if !filepath.IsAbs(repl) {
+				if strings.HasPrefix(repl, ".") && !filepath.IsAbs(repl) {
 					repl, err = filepath.Abs(repl)
 					if err != nil {
 						log.Fatalf("[FATAL] %v", err)
@@ -288,7 +288,9 @@ func trapSignals(ctx context.Context, cancel context.CancelFunc) {
 func splitWith(arg string) (module, version, replace string, err error) {
 	const versionSplit, replaceSplit = "@", "="
 
-	parts := strings.SplitN(arg, versionSplit, 2)
+	modules := strings.SplitN(arg, replaceSplit, 2)
+
+	parts := strings.SplitN(modules[0], versionSplit, 2)
 	module = parts[0]
 
 	if len(parts) == 1 {
```

Test run:
```
=== RUN   TestSplitWith
    caddyserver/xcaddy/cmd/xcaddy/main_test.go:72: Test 2: Expected module 'replace' but got '' (input='module@version=replace')
    caddyserver/xcaddy/cmd/xcaddy/main_test.go:72: Test 3: Expected module 'replace' but got '' (input='module=replace')
```

**Comment by francislavoie** [comment]
It also needs to support `module=replace@version`

**Comment by Mohammed90** [comment]
> It also needs to support `module=replace@version`

Hence

> but didn't finish it

😄
