### ISSUE TITLE
Is there a way that I can empty the `buildid` so the built would be reproducible?

### ISSUE THREAD

**Issue by IceCodeNew** [caddyserver/xcaddy#53]
Is there a way that I can empty the `buildid` so the built would be reproducible?

**Comment by mholt** [comment]
You mean like this? https://github.com/golang/go/issues/33772

If you have a moment, could you verify that specifying `-ldflags=-buildid=` (preferably by adding this into the commands `xcaddy` runs) successfully removes the build ID and does in fact produce byte-for-byte identical builds, even in different working dirs?

**Comment by Mohammed90** [comment]
> You mean like this? https://github.com/golang/go/issues/33772
> 
> If you have a moment, could you verify that specifying `-ldflags=-buildid=` (preferably by adding this into the commands `xcaddy` runs) successfully removes the build ID and does in fact produce byte-for-byte identical builds, even in different working dirs?

I'm confused. We already use `-trimpath` and the cited issue shows it was fixed specifically for `-trimpath` so the ldflag is no longer needed. Is that not the case?

**Comment by mholt** [comment]
@Mohammed90 I think you're right, but apparently we also need to blank out the buildid.

**Comment by Mohammed90** [comment]
Just tested on MacOS:
```
 ~ diff <(hexdump -Cv ./caddy-1) <(hexdump -Cv ./caddy-2)
 ~ ls buildenv_2021-03-11-0
buildenv_2021-03-11-0159.953366929/  buildenv_2021-03-11-0200.745738981/
```
Two different dirs, no diffs across the built binaries.

**Comment by mholt** [comment]
In that case, the builds should already be reproducible. Thanks for checking on that!

Will close, but feel free to continue discussion if needed.
