### ISSUE TITLE
auto upgrade caddy version

### ISSUE THREAD

**Issue by enefry** [caddyserver/xcaddy#58]
I try to build caddy 2.3.0 but xcaddy auto upgraded to v2.4.0-beta.1

 xcaddy build v2.3.0 \
    --with github.com/RussellLuo/caddy-ext/ratelimit \
    --with github.com/abiosoft/caddy-hmac \
    --with github.com/caddy-dns/cloudflare \
    --with github.com/caddyserver/jsonc-adapter \
    --with github.com/casbin/caddy-authz/v2 \
    --with github.com/greenpau/caddy-auth-jwt \
    --with github.com/greenpau/caddy-auth-portal \
    --with github.com/kirsch33/realip \
    --with github.com/sjtug/caddy2-filter
2021/03/30 13:16:16 [INFO] Temporary folder: /tmp/buildenv_2021-03-30-1316.375702467
2021/03/30 13:16:16 [INFO] Writing main module: /tmp/buildenv_2021-03-30-1316.375702467/main.go
2021/03/30 13:16:16 [INFO] Initializing Go module
2021/03/30 13:16:16 [INFO] exec (timeout=10s): /usr/local/bin/go mod init caddy
go: creating new go.mod: module caddy
go: to add module requirements and sums:
	go mod tidy
2021/03/30 13:16:16 [INFO] Pinning versions
2021/03/30 13:16:16 [INFO] exec (timeout=0s): /usr/local/bin/go get -d -v github.com/caddyserver/caddy/v2@v2.3.0
go get: added github.com/caddyserver/caddy/v2 v2.3.0
2021/03/30 13:16:20 [INFO] exec (timeout=0s): /usr/local/bin/go get -d -v github.com/RussellLuo/caddy-ext/ratelimit
go get: added github.com/RussellLuo/caddy-ext/ratelimit v0.0.0-20210216051744-6266d94e5ad9
2021/03/30 13:16:24 [INFO] exec (timeout=0s): /usr/local/bin/go get -d -v github.com/abiosoft/caddy-hmac
go get: added github.com/abiosoft/caddy-hmac v0.0.0-20200528051232-71b2c4bbf374
2021/03/30 13:16:25 [INFO] exec (timeout=0s): /usr/local/bin/go get -d -v github.com/caddy-dns/cloudflare
go get: added github.com/caddy-dns/cloudflare v0.0.0-20210312233109-9d3a8971aaa8
**go get: upgraded github.com/caddyserver/caddy/v2 v2.3.0 => v2.4.0-beta.1**
2021/03/30 13:16:26 [INFO] exec (timeout=0s): /usr/local/bin/go get -d -v github.com/caddyserver/jsonc-adapter
go get: added github.com/caddyserver/jsonc-adapter v0.0.0-20200325004025-825ee096306c
2021/03/30 13:16:27 [INFO] exec (timeout=0s): /usr/local/bin/go get -d -v github.com/casbin/caddy-authz/v2
go get: added github.com/casbin/caddy-authz/v2 v2.0.0
2021/03/30 13:16:29 [INFO] exec (timeout=0s): /usr/local/bin/go get -d -v github.com/greenpau/caddy-auth-jwt
go get: added github.com/greenpau/caddy-auth-jwt v1.2.7
2021/03/30 13:16:30 [INFO] exec (timeout=0s): /usr/local/bin/go get -d -v github.com/greenpau/caddy-auth-portal
go get: added github.com/greenpau/caddy-auth-portal v1.4.6
2021/03/30 13:16:32 [INFO] exec (timeout=0s): /usr/local/bin/go get -d -v github.com/kirsch33/realip
go get: added github.com/kirsch33/realip v1.5.2
2021/03/30 13:16:33 [INFO] exec (timeout=0s): /usr/local/bin/go get -d -v github.com/sjtug/caddy2-filter
go get: added github.com/sjtug/caddy2-filter v0.0.0-20210315003910-95ab1651d436
2021/03/30 13:16:34 [INFO] Build environment ready
2021/03/30 13:16:34 [INFO] Building Caddy
2021/03/30 13:16:34 [INFO] exec (timeout=0s): /usr/local/bin/go mod tidy
go: finding module for package github.com/go-redis/redis
go: found github.com/go-redis/redis in github.com/go-redis/redis v6.15.9+incompatible
2021/03/30 13:16:35 [INFO] exec (timeout=0s): /usr/local/bin/go build -o /root/go/bin/caddy -ldflags -w -s -trimpath
2021/03/30 13:16:38 [INFO] Build complete: ./caddy
2021/03/30 13:16:38 [INFO] Cleaning up temporary folder: /tmp/buildenv_2021-03-30-1316.375702467

**Comment by francislavoie** [comment]
This is a known issue with the CloudFlare plugin. See the discussion in https://github.com/caddyserver/xcaddy/issues/54. you'll need to specify an older commit of the CloudFlare plugin to properly build with v2.3.0. Sorry.
