### ISSUE TITLE
Allow building a debug version of the output

### ISSUE THREAD

**Issue by ggicci** [caddyserver/xcaddy#61]
Since `xcaddy build` command passed `-ldflag "-w -s"` flags to `go build` command by default, which turns off DWARF debug information. The output can't be utlized in a debug tool.

It will be helpful if we were given a chance to remove these flags.

For my use case, I'm developing a Caddy module. And I'm using `xcaddy` to build the test release. I really hope I can build a debug version of `caddy` with my module under development. So that I can debug it in VSCode.

**Comment by mholt** [comment]
Done in #62 (thanks!)
