### ISSUE TITLE
[ERROR] exec [go list -m -json all]

### ISSUE THREAD

**Issue by doums** [caddyserver/xcaddy#77]
Hi,

When I run
```shell
xcaddy alpine --with github.com/caddy-dns/duckdns
```
the build fails and I got the following error:
```
go list -m: not using modules
[ERROR] exec [go list -m -json all]: exit status 1:
```

go version go1.17.3 linux/arm64

**Comment by francislavoie** [comment]
`xcaddy alpine` is not a valid command. You should be running `xcaddy build`.

**Comment by doums** [comment]
Oh! yeah I forgot to put `build` subcommand...

But is it possible to build specifically the "alpine" version ?

**Comment by francislavoie** [comment]
There's no such thing, `alpine` is a linux distro. Go builds are OS/arch-specific. So any linux/amd64 build for example will run on any linux distro.

**Comment by doums** [comment]
Yes bad question, okay thank you, I close the issue.

**Comment by francislavoie** [comment]
No worries! 😄
