### ISSUE TITLE
Build from master branch directly

### ISSUE THREAD

**Issue by lenovouser** [caddyserver/xcaddy#87]
To currently build from the latest commit available it seems like I have to do two steps:

 - Download the caddy repository
 - Execute `xcaddy --with domain.com/my-plugin`

Something like `xcaddy build edge --with domain.com/my-plugin`, which just does it all for you in one go, so that you can test your plugins with the latest commit available online for example would be nice. It's completely fine to do the repository step like right now, but I thought it'd be nice to have a command like that for a little bit of speed up in the workflow.

**Comment by francislavoie** [comment]
`xcaddy build master` already works 🤔

**Comment by lenovouser** [comment]
I was trying so many things like commit hashes etc., why didn't I think of that 😭 I'll open a PR to add it to the readme, okay?

**Comment by francislavoie** [comment]
Sure, makes sense to clarify that `<caddy_version>` can be any git ref
