### ISSUE TITLE
How can i force xcaddy to use another of my installed versions of go?

### ISSUE THREAD

**Issue by kmpm** [caddyserver/xcaddy#96]
I have go 1.18 as my base version and have installed 1.17.9 as described in https://go.dev/doc/manage-install .
So if i run `go version` I get `go version go1.18 windows/amd64` and if I do `go1.17.9 version` i get `go version go1.17.9 windows/amd64`

When i try to build a new caddy with xcaddy I stumble upon issue #90 .

Is there a way to force xcaddy to pick the 1.17 go environment?

**Comment by mholt** [comment]
Thanks for the PR. That's a good question, I agree we could support this easily enough. I'll comment on the PR. Cheers!
