### ISSUE TITLE
How to build the plugin in debug mode?

### ISSUE THREAD

**Issue by StarpTech** [caddyserver/xcaddy#98]
Hi, how can I use a debugger to go through the module with e.g Goland IDE?

**Comment by mholt** [comment]
What do you mean by "debug mode"?

**Comment by StarpTech** [comment]
I'd like to add a breakpoint in the code.

**Comment by StarpTech** [comment]
I answered it myself :smile: Of course, I can just create a `main.go` like https://github.com/caddyserver/caddy/blob/master/cmd/caddy/main.go

**Comment by mholt** [comment]
Hmm, I'm not sure, I don't really use debuggers with Go. Glad you found something that works for you though!

**Comment by StarpTech** [comment]
Out of curiosity, how do you debug then? Println?

**Comment by francislavoie** [comment]
Yeah, I think we tend to just spam `fmt.Printf("%+v\n", foo)` all over to debug 😅 for me it's a habit from being a PHP dev, I find it quick enough to just run `go build && ./caddy run` repeatedly to test stuff

**Comment by StarpTech** [comment]
I created a [`cmd/server/main.go`](https://github.com/caddyserver/caddy/blob/master/cmd/caddy/main.go?rgh-link-date=2022-04-21T21%3A16%3A21Z) and referenced my module in it. Then there is no difference between caddy module development and hacking on a regular go project. For Goland and Vscode you only need to add `run` to the program arguments in the debugger profile.
